sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1234"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDsEBkCe3cpqAfHAVxu
    access-key-secret: qNqBOmarYzN49LNdxY3mW9pAQwrCIp
    bucket-name: sky-itheima-castxxx
  file:
    upload-dir: E:/practice/JAVA_Studying/sky_delivery/sky-take-out/sky-server/src/main/resources/uploads
    access-url: http://localhost:8080/uploads
  redis:
    host: localhost
    port: 6379
    password: "123456"
    database: 10
  wechat:
    appid: wxee6cd3455163d845
    secret: 4886262b3405fc02fbe14cd437d0542b
